spring:
  application:
    name: EUREKA
server:
  port: 8761
eureka:
  instance:
    leaseExpirationDurationInSeconds: 5
    leaseRenewalIntervalInSeconds: 3
    preferIpAddress: false
  client:
    registerWithEureka: false
    fetchRegistry: true